### ISSUE TITLE
Action to clean zip (one or all)

### ISSUE THREAD

**Issue by flancer64** [flancer32/pwa-ra-desk#83]
> может есть смысл добавить action (действие) в карточку упражнения в админке для зачистки конкретного zip'а с анимацией (серверный кэш)? Или даже можно действие для зачистки всех zip'ов поставить на грид с упражнениями. Или на зачистку и регенерацию всех zip'ов.

**Comment by flancer64** [comment]
Так как время обновления отдельного zip'а незначительно, то в карточке упражнения выполнение операции происходит без дополнительного подтверждения:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/7d0c2e44-6fdb-4d75-bdbf-eed00154cdbc)

**Comment by flancer64** [comment]
выложил на live & pilot

**Comment by minkinr** [comment]
отлично. единичные ещё в плане?

чт, 7 сент. 2023 г., 14:05 Alex Gusev ***@***.***>:

**Comment by minkinr** [comment]
спасибо. отлично. 14:07, 7 сентября 2023 г., Alex Gusev ***@***.***>:
Так как время обновления отдельного zip'а незначительно, то в карточке упражнения выполнение операции происходит без дополнительного подтверждения:


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты
